insert into TYPEEFFECT values('normal','normal',100);
insert into TYPEEFFECT values('normal','fighting',100);
insert into TYPEEFFECT values('normal','flying',100);
insert into TYPEEFFECT values('normal','poison',100);
insert into TYPEEFFECT values('normal','ground',100);
insert into TYPEEFFECT values('normal','rock',100);
insert into TYPEEFFECT values('normal','bug',100);
insert into TYPEEFFECT values('normal','ghost',100);
insert into TYPEEFFECT values('normal','steel',100);
insert into TYPEEFFECT values('normal','fire',100);
insert into TYPEEFFECT values('normal','water',100);
insert into TYPEEFFECT values('normal','grass',100);
insert into TYPEEFFECT values('normal','electric',100);
insert into TYPEEFFECT values('normal','psychic',100);
insert into TYPEEFFECT values('normal','ice',100);
insert into TYPEEFFECT values('normal','dragon',100);
insert into TYPEEFFECT values('normal','dark',100);
insert into TYPEEFFECT values('normal','fairy',100);
insert into TYPEEFFECT values('fighting','normal',100);
insert into TYPEEFFECT values('fighting','fighting',100);
insert into TYPEEFFECT values('fighting','flying',100);
insert into TYPEEFFECT values('fighting','poison',100);
insert into TYPEEFFECT values('fighting','ground',100);
insert into TYPEEFFECT values('fighting','rock',100);
insert into TYPEEFFECT values('fighting','bug',100);
insert into TYPEEFFECT values('fighting','ghost',100);
insert into TYPEEFFECT values('fighting','steel',100);
insert into TYPEEFFECT values('fighting','fire',100);
insert into TYPEEFFECT values('fighting','water',100);
insert into TYPEEFFECT values('fighting','grass',100);
insert into TYPEEFFECT values('fighting','electric',100);
insert into TYPEEFFECT values('fighting','psychic',100);
insert into TYPEEFFECT values('fighting','ice',100);
insert into TYPEEFFECT values('fighting','dragon',100);
insert into TYPEEFFECT values('fighting','dark',100);
insert into TYPEEFFECT values('fighting','fairy',100);
insert into TYPEEFFECT values('flying','normal',100);
insert into TYPEEFFECT values('flying','fighting',100);
insert into TYPEEFFECT values('flying','flying',100);
insert into TYPEEFFECT values('flying','poison',100);
insert into TYPEEFFECT values('flying','ground',100);
insert into TYPEEFFECT values('flying','rock',100);
insert into TYPEEFFECT values('flying','bug',100);
insert into TYPEEFFECT values('flying','ghost',100);
insert into TYPEEFFECT values('flying','steel',100);
insert into TYPEEFFECT values('flying','fire',100);
insert into TYPEEFFECT values('flying','water',100);
insert into TYPEEFFECT values('flying','grass',100);
insert into TYPEEFFECT values('flying','electric',100);
insert into TYPEEFFECT values('flying','psychic',100);
insert into TYPEEFFECT values('flying','ice',100);
insert into TYPEEFFECT values('flying','dragon',100);
insert into TYPEEFFECT values('flying','dark',100);
insert into TYPEEFFECT values('flying','fairy',100);
insert into TYPEEFFECT values('poison','normal',100);
insert into TYPEEFFECT values('poison','fighting',100);
insert into TYPEEFFECT values('poison','flying',100);
insert into TYPEEFFECT values('poison','poison',100);
insert into TYPEEFFECT values('poison','ground',100);
insert into TYPEEFFECT values('poison','rock',100);
insert into TYPEEFFECT values('poison','bug',100);
insert into TYPEEFFECT values('poison','ghost',100);
insert into TYPEEFFECT values('poison','steel',100);
insert into TYPEEFFECT values('poison','fire',100);
insert into TYPEEFFECT values('poison','water',100);
insert into TYPEEFFECT values('poison','grass',100);
insert into TYPEEFFECT values('poison','electric',100);
insert into TYPEEFFECT values('poison','psychic',100);
insert into TYPEEFFECT values('poison','ice',100);
insert into TYPEEFFECT values('poison','dragon',100);
insert into TYPEEFFECT values('poison','dark',100);
insert into TYPEEFFECT values('poison','fairy',100);
insert into TYPEEFFECT values('ground','normal',100);
insert into TYPEEFFECT values('ground','fighting',100);
insert into TYPEEFFECT values('ground','flying',100);
insert into TYPEEFFECT values('ground','poison',100);
insert into TYPEEFFECT values('ground','ground',100);
insert into TYPEEFFECT values('ground','rock',100);
insert into TYPEEFFECT values('ground','bug',100);
insert into TYPEEFFECT values('ground','ghost',100);
insert into TYPEEFFECT values('ground','steel',100);
insert into TYPEEFFECT values('ground','fire',100);
insert into TYPEEFFECT values('ground','water',100);
insert into TYPEEFFECT values('ground','grass',100);
insert into TYPEEFFECT values('ground','electric',100);
insert into TYPEEFFECT values('ground','psychic',100);
insert into TYPEEFFECT values('ground','ice',100);
insert into TYPEEFFECT values('ground','dragon',100);
insert into TYPEEFFECT values('ground','dark',100);
insert into TYPEEFFECT values('ground','fairy',100);
insert into TYPEEFFECT values('rock','normal',100);
insert into TYPEEFFECT values('rock','fighting',100);
insert into TYPEEFFECT values('rock','flying',100);
insert into TYPEEFFECT values('rock','poison',100);
insert into TYPEEFFECT values('rock','ground',100);
insert into TYPEEFFECT values('rock','rock',100);
insert into TYPEEFFECT values('rock','bug',100);
insert into TYPEEFFECT values('rock','ghost',100);
insert into TYPEEFFECT values('rock','steel',100);
insert into TYPEEFFECT values('rock','fire',100);
insert into TYPEEFFECT values('rock','water',100);
insert into TYPEEFFECT values('rock','grass',100);
insert into TYPEEFFECT values('rock','electric',100);
insert into TYPEEFFECT values('rock','psychic',100);
insert into TYPEEFFECT values('rock','ice',100);
insert into TYPEEFFECT values('rock','dragon',100);
insert into TYPEEFFECT values('rock','dark',100);
insert into TYPEEFFECT values('rock','fairy',100);
insert into TYPEEFFECT values('bug','normal',100);
insert into TYPEEFFECT values('bug','fighting',100);
insert into TYPEEFFECT values('bug','flying',100);
insert into TYPEEFFECT values('bug','poison',100);
insert into TYPEEFFECT values('bug','ground',100);
insert into TYPEEFFECT values('bug','rock',100);
insert into TYPEEFFECT values('bug','bug',100);
insert into TYPEEFFECT values('bug','ghost',100);
insert into TYPEEFFECT values('bug','steel',100);
insert into TYPEEFFECT values('bug','fire',100);
insert into TYPEEFFECT values('bug','water',100);
insert into TYPEEFFECT values('bug','grass',100);
insert into TYPEEFFECT values('bug','electric',100);
insert into TYPEEFFECT values('bug','psychic',100);
insert into TYPEEFFECT values('bug','ice',100);
insert into TYPEEFFECT values('bug','dragon',100);
insert into TYPEEFFECT values('bug','dark',100);
insert into TYPEEFFECT values('bug','fairy',100);
insert into TYPEEFFECT values('ghost','normal',100);
insert into TYPEEFFECT values('ghost','fighting',100);
insert into TYPEEFFECT values('ghost','flying',100);
insert into TYPEEFFECT values('ghost','poison',100);
insert into TYPEEFFECT values('ghost','ground',100);
insert into TYPEEFFECT values('ghost','rock',100);
insert into TYPEEFFECT values('ghost','bug',100);
insert into TYPEEFFECT values('ghost','ghost',100);
insert into TYPEEFFECT values('ghost','steel',100);
insert into TYPEEFFECT values('ghost','fire',100);
insert into TYPEEFFECT values('ghost','water',100);
insert into TYPEEFFECT values('ghost','grass',100);
insert into TYPEEFFECT values('ghost','electric',100);
insert into TYPEEFFECT values('ghost','psychic',100);
insert into TYPEEFFECT values('ghost','ice',100);
insert into TYPEEFFECT values('ghost','dragon',100);
insert into TYPEEFFECT values('ghost','dark',100);
insert into TYPEEFFECT values('ghost','fairy',100);
insert into TYPEEFFECT values('steel','normal',100);
insert into TYPEEFFECT values('steel','fighting',100);
insert into TYPEEFFECT values('steel','flying',100);
insert into TYPEEFFECT values('steel','poison',100);
insert into TYPEEFFECT values('steel','ground',100);
insert into TYPEEFFECT values('steel','rock',100);
insert into TYPEEFFECT values('steel','bug',100);
insert into TYPEEFFECT values('steel','ghost',100);
insert into TYPEEFFECT values('steel','steel',100);
insert into TYPEEFFECT values('steel','fire',100);
insert into TYPEEFFECT values('steel','water',100);
insert into TYPEEFFECT values('steel','grass',100);
insert into TYPEEFFECT values('steel','electric',100);
insert into TYPEEFFECT values('steel','psychic',100);
insert into TYPEEFFECT values('steel','ice',100);
insert into TYPEEFFECT values('steel','dragon',100);
insert into TYPEEFFECT values('steel','dark',100);
insert into TYPEEFFECT values('steel','fairy',100);
insert into TYPEEFFECT values('fire','normal',100);
insert into TYPEEFFECT values('fire','fighting',100);
insert into TYPEEFFECT values('fire','flying',100);
insert into TYPEEFFECT values('fire','poison',100);
insert into TYPEEFFECT values('fire','ground',100);
insert into TYPEEFFECT values('fire','rock',100);
insert into TYPEEFFECT values('fire','bug',100);
insert into TYPEEFFECT values('fire','ghost',100);
insert into TYPEEFFECT values('fire','steel',100);
insert into TYPEEFFECT values('fire','fire',100);
insert into TYPEEFFECT values('fire','water',100);
insert into TYPEEFFECT values('fire','grass',100);
insert into TYPEEFFECT values('fire','electric',100);
insert into TYPEEFFECT values('fire','psychic',100);
insert into TYPEEFFECT values('fire','ice',100);
insert into TYPEEFFECT values('fire','dragon',100);
insert into TYPEEFFECT values('fire','dark',100);
insert into TYPEEFFECT values('fire','fairy',100);
insert into TYPEEFFECT values('water','normal',100);
insert into TYPEEFFECT values('water','fighting',100);
insert into TYPEEFFECT values('water','flying',100);
insert into TYPEEFFECT values('water','poison',100);
insert into TYPEEFFECT values('water','ground',100);
insert into TYPEEFFECT values('water','rock',100);
insert into TYPEEFFECT values('water','bug',100);
insert into TYPEEFFECT values('water','ghost',100);
insert into TYPEEFFECT values('water','steel',100);
insert into TYPEEFFECT values('water','fire',100);
insert into TYPEEFFECT values('water','water',100);
insert into TYPEEFFECT values('water','grass',100);
insert into TYPEEFFECT values('water','electric',100);
insert into TYPEEFFECT values('water','psychic',100);
insert into TYPEEFFECT values('water','ice',100);
insert into TYPEEFFECT values('water','dragon',100);
insert into TYPEEFFECT values('water','dark',100);
insert into TYPEEFFECT values('water','fairy',100);
insert into TYPEEFFECT values('grass','normal',100);
insert into TYPEEFFECT values('grass','fighting',100);
insert into TYPEEFFECT values('grass','flying',100);
insert into TYPEEFFECT values('grass','poison',100);
insert into TYPEEFFECT values('grass','ground',100);
insert into TYPEEFFECT values('grass','rock',100);
insert into TYPEEFFECT values('grass','bug',100);
insert into TYPEEFFECT values('grass','ghost',100);
insert into TYPEEFFECT values('grass','steel',100);
insert into TYPEEFFECT values('grass','fire',100);
insert into TYPEEFFECT values('grass','water',100);
insert into TYPEEFFECT values('grass','grass',100);
insert into TYPEEFFECT values('grass','electric',100);
insert into TYPEEFFECT values('grass','psychic',100);
insert into TYPEEFFECT values('grass','ice',100);
insert into TYPEEFFECT values('grass','dragon',100);
insert into TYPEEFFECT values('grass','dark',100);
insert into TYPEEFFECT values('grass','fairy',100);
insert into TYPEEFFECT values('electric','normal',100);
insert into TYPEEFFECT values('electric','fighting',100);
insert into TYPEEFFECT values('electric','flying',100);
insert into TYPEEFFECT values('electric','poison',100);
insert into TYPEEFFECT values('electric','ground',100);
insert into TYPEEFFECT values('electric','rock',100);
insert into TYPEEFFECT values('electric','bug',100);
insert into TYPEEFFECT values('electric','ghost',100);
insert into TYPEEFFECT values('electric','steel',100);
insert into TYPEEFFECT values('electric','fire',100);
insert into TYPEEFFECT values('electric','water',100);
insert into TYPEEFFECT values('electric','grass',100);
insert into TYPEEFFECT values('electric','electric',100);
insert into TYPEEFFECT values('electric','psychic',100);
insert into TYPEEFFECT values('electric','ice',100);
insert into TYPEEFFECT values('electric','dragon',100);
insert into TYPEEFFECT values('electric','dark',100);
insert into TYPEEFFECT values('electric','fairy',100);
insert into TYPEEFFECT values('psychic','normal',100);
insert into TYPEEFFECT values('psychic','fighting',100);
insert into TYPEEFFECT values('psychic','flying',100);
insert into TYPEEFFECT values('psychic','poison',100);
insert into TYPEEFFECT values('psychic','ground',100);
insert into TYPEEFFECT values('psychic','rock',100);
insert into TYPEEFFECT values('psychic','bug',100);
insert into TYPEEFFECT values('psychic','ghost',100);
insert into TYPEEFFECT values('psychic','steel',100);
insert into TYPEEFFECT values('psychic','fire',100);
insert into TYPEEFFECT values('psychic','water',100);
insert into TYPEEFFECT values('psychic','grass',100);
insert into TYPEEFFECT values('psychic','electric',100);
insert into TYPEEFFECT values('psychic','psychic',100);
insert into TYPEEFFECT values('psychic','ice',100);
insert into TYPEEFFECT values('psychic','dragon',100);
insert into TYPEEFFECT values('psychic','dark',100);
insert into TYPEEFFECT values('psychic','fairy',100);
insert into TYPEEFFECT values('ice','normal',100);
insert into TYPEEFFECT values('ice','fighting',100);
insert into TYPEEFFECT values('ice','flying',100);
insert into TYPEEFFECT values('ice','poison',100);
insert into TYPEEFFECT values('ice','ground',100);
insert into TYPEEFFECT values('ice','rock',100);
insert into TYPEEFFECT values('ice','bug',100);
insert into TYPEEFFECT values('ice','ghost',100);
insert into TYPEEFFECT values('ice','steel',100);
insert into TYPEEFFECT values('ice','fire',100);
insert into TYPEEFFECT values('ice','water',100);
insert into TYPEEFFECT values('ice','grass',100);
insert into TYPEEFFECT values('ice','electric',100);
insert into TYPEEFFECT values('ice','psychic',100);
insert into TYPEEFFECT values('ice','ice',100);
insert into TYPEEFFECT values('ice','dragon',100);
insert into TYPEEFFECT values('ice','dark',100);
insert into TYPEEFFECT values('ice','fairy',100);
insert into TYPEEFFECT values('dragon','normal',100);
insert into TYPEEFFECT values('dragon','fighting',100);
insert into TYPEEFFECT values('dragon','flying',100);
insert into TYPEEFFECT values('dragon','poison',100);
insert into TYPEEFFECT values('dragon','ground',100);
insert into TYPEEFFECT values('dragon','rock',100);
insert into TYPEEFFECT values('dragon','bug',100);
insert into TYPEEFFECT values('dragon','ghost',100);
insert into TYPEEFFECT values('dragon','steel',100);
insert into TYPEEFFECT values('dragon','fire',100);
insert into TYPEEFFECT values('dragon','water',100);
insert into TYPEEFFECT values('dragon','grass',100);
insert into TYPEEFFECT values('dragon','electric',100);
insert into TYPEEFFECT values('dragon','psychic',100);
insert into TYPEEFFECT values('dragon','ice',100);
insert into TYPEEFFECT values('dragon','dragon',100);
insert into TYPEEFFECT values('dragon','dark',100);
insert into TYPEEFFECT values('dragon','fairy',100);
insert into TYPEEFFECT values('dark','normal',100);
insert into TYPEEFFECT values('dark','fighting',100);
insert into TYPEEFFECT values('dark','flying',100);
insert into TYPEEFFECT values('dark','poison',100);
insert into TYPEEFFECT values('dark','ground',100);
insert into TYPEEFFECT values('dark','rock',100);
insert into TYPEEFFECT values('dark','bug',100);
insert into TYPEEFFECT values('dark','ghost',100);
insert into TYPEEFFECT values('dark','steel',100);
insert into TYPEEFFECT values('dark','fire',100);
insert into TYPEEFFECT values('dark','water',100);
insert into TYPEEFFECT values('dark','grass',100);
insert into TYPEEFFECT values('dark','electric',100);
insert into TYPEEFFECT values('dark','psychic',100);
insert into TYPEEFFECT values('dark','ice',100);
insert into TYPEEFFECT values('dark','dragon',100);
insert into TYPEEFFECT values('dark','dark',100);
insert into TYPEEFFECT values('dark','fairy',100);
insert into TYPEEFFECT values('fairy','normal',100);
insert into TYPEEFFECT values('fairy','fighting',100);
insert into TYPEEFFECT values('fairy','flying',100);
insert into TYPEEFFECT values('fairy','poison',100);
insert into TYPEEFFECT values('fairy','ground',100);
insert into TYPEEFFECT values('fairy','rock',100);
insert into TYPEEFFECT values('fairy','bug',100);
insert into TYPEEFFECT values('fairy','ghost',100);
insert into TYPEEFFECT values('fairy','steel',100);
insert into TYPEEFFECT values('fairy','fire',100);
insert into TYPEEFFECT values('fairy','water',100);
insert into TYPEEFFECT values('fairy','grass',100);
insert into TYPEEFFECT values('fairy','electric',100);
insert into TYPEEFFECT values('fairy','psychic',100);
insert into TYPEEFFECT values('fairy','ice',100);
insert into TYPEEFFECT values('fairy','dragon',100);
insert into TYPEEFFECT values('fairy','dark',100);
insert into TYPEEFFECT values('fairy','fairy',100);
update TYPEEFFECT set multfactor=0 where attackertype='normal' and receivertype='ghost';
update TYPEEFFECT set multfactor=50 where attackertype='normal' and receivertype='rock';
update TYPEEFFECT set multfactor=50 where attackertype='normal' and receivertype='steel';
update TYPEEFFECT set multfactor=0 where attackertype='fighting' and receivertype='ghost';
update TYPEEFFECT set multfactor=50 where attackertype='fighting' and receivertype='flying';
update TYPEEFFECT set multfactor=50 where attackertype='fighting' and receivertype='poison';
update TYPEEFFECT set multfactor=50 where attackertype='fighting' and receivertype='bug';
update TYPEEFFECT set multfactor=50 where attackertype='fighting' and receivertype='psychic';
update TYPEEFFECT set multfactor=50 where attackertype='fighting' and receivertype='fairy';
update TYPEEFFECT set multfactor=200 where attackertype='fighting' and receivertype='normal';
update TYPEEFFECT set multfactor=200 where attackertype='fighting' and receivertype='rock';
update TYPEEFFECT set multfactor=200 where attackertype='fighting' and receivertype='steel';
update TYPEEFFECT set multfactor=200 where attackertype='fighting' and receivertype='ice';
update TYPEEFFECT set multfactor=200 where attackertype='fighting' and receivertype='dark';
update TYPEEFFECT set multfactor=50 where attackertype='flying' and receivertype='rock';
update TYPEEFFECT set multfactor=50 where attackertype='flying' and receivertype='steel';
update TYPEEFFECT set multfactor=50 where attackertype='flying' and receivertype='electric';
update TYPEEFFECT set multfactor=200 where attackertype='flying' and receivertype='fighting';
update TYPEEFFECT set multfactor=200 where attackertype='flying' and receivertype='bug';
update TYPEEFFECT set multfactor=200 where attackertype='flying' and receivertype='grass';
update TYPEEFFECT set multfactor=0 where attackertype='poison' and receivertype='steel';
update TYPEEFFECT set multfactor=50 where attackertype='poison' and receivertype='poison';
update TYPEEFFECT set multfactor=50 where attackertype='poison' and receivertype='ground';
update TYPEEFFECT set multfactor=50 where attackertype='poison' and receivertype='rock';
update TYPEEFFECT set multfactor=50 where attackertype='poison' and receivertype='ghost';
update TYPEEFFECT set multfactor=200 where attackertype='poison' and receivertype='grass';
update TYPEEFFECT set multfactor=200 where attackertype='poison' and receivertype='fairy';
update TYPEEFFECT set multfactor=0 where attackertype='ground' and receivertype='flying';
update TYPEEFFECT set multfactor=50 where attackertype='ground' and receivertype='bug';
update TYPEEFFECT set multfactor=50 where attackertype='ground' and receivertype='grass';
update TYPEEFFECT set multfactor=200 where attackertype='ground' and receivertype='poison';
update TYPEEFFECT set multfactor=200 where attackertype='ground' and receivertype='rock';
update TYPEEFFECT set multfactor=200 where attackertype='ground' and receivertype='steel';
update TYPEEFFECT set multfactor=200 where attackertype='ground' and receivertype='fire';
update TYPEEFFECT set multfactor=200 where attackertype='ground' and receivertype='electric';
update TYPEEFFECT set multfactor=50 where attackertype='rock' and receivertype='fighting';
update TYPEEFFECT set multfactor=50 where attackertype='rock' and receivertype='ground';
update TYPEEFFECT set multfactor=50 where attackertype='rock' and receivertype='steel';
update TYPEEFFECT set multfactor=200 where attackertype='rock' and receivertype='flying';
update TYPEEFFECT set multfactor=200 where attackertype='rock' and receivertype='bug';
update TYPEEFFECT set multfactor=200 where attackertype='rock' and receivertype='fire';
update TYPEEFFECT set multfactor=200 where attackertype='rock' and receivertype='ice';
update TYPEEFFECT set multfactor=50 where attackertype='bug' and receivertype='fighting';
update TYPEEFFECT set multfactor=50 where attackertype='bug' and receivertype='flying';
update TYPEEFFECT set multfactor=50 where attackertype='bug' and receivertype='poison';
update TYPEEFFECT set multfactor=50 where attackertype='bug' and receivertype='ghost';
update TYPEEFFECT set multfactor=50 where attackertype='bug' and receivertype='steel';
update TYPEEFFECT set multfactor=50 where attackertype='bug' and receivertype='fire';
update TYPEEFFECT set multfactor=50 where attackertype='bug' and receivertype='fairy';
update TYPEEFFECT set multfactor=200 where attackertype='bug' and receivertype='grass';
update TYPEEFFECT set multfactor=200 where attackertype='bug' and receivertype='psychic';
update TYPEEFFECT set multfactor=200 where attackertype='bug' and receivertype='dark';
update TYPEEFFECT set multfactor=0 where attackertype='ghost' and receivertype='normal';
update TYPEEFFECT set multfactor=50 where attackertype='ghost' and receivertype='dark';
update TYPEEFFECT set multfactor=200 where attackertype='ghost' and receivertype='ghost';
update TYPEEFFECT set multfactor=200 where attackertype='ghost' and receivertype='psychic';
update TYPEEFFECT set multfactor=50 where attackertype='steel' and receivertype='steel';
update TYPEEFFECT set multfactor=50 where attackertype='steel' and receivertype='fire';
update TYPEEFFECT set multfactor=50 where attackertype='steel' and receivertype='water';
update TYPEEFFECT set multfactor=50 where attackertype='steel' and receivertype='electric';
update TYPEEFFECT set multfactor=200 where attackertype='steel' and receivertype='rock';
update TYPEEFFECT set multfactor=200 where attackertype='steel' and receivertype='ice';
update TYPEEFFECT set multfactor=200 where attackertype='steel' and receivertype='fairy';
update TYPEEFFECT set multfactor=50 where attackertype='fire' and receivertype='rock';
update TYPEEFFECT set multfactor=50 where attackertype='fire' and receivertype='fire';
update TYPEEFFECT set multfactor=50 where attackertype='fire' and receivertype='water';
update TYPEEFFECT set multfactor=50 where attackertype='fire' and receivertype='dragon';
update TYPEEFFECT set multfactor=200 where attackertype='fire' and receivertype='bug';
update TYPEEFFECT set multfactor=200 where attackertype='fire' and receivertype='steel';
update TYPEEFFECT set multfactor=200 where attackertype='fire' and receivertype='grass';
update TYPEEFFECT set multfactor=200 where attackertype='fire' and receivertype='ice';
update TYPEEFFECT set multfactor=50 where attackertype='water' and receivertype='water';
update TYPEEFFECT set multfactor=50 where attackertype='water' and receivertype='grass';
update TYPEEFFECT set multfactor=50 where attackertype='water' and receivertype='dragon';
update TYPEEFFECT set multfactor=200 where attackertype='water' and receivertype='ground';
update TYPEEFFECT set multfactor=200 where attackertype='water' and receivertype='rock';
update TYPEEFFECT set multfactor=200 where attackertype='water' and receivertype='fire';
update TYPEEFFECT set multfactor=50 where attackertype='grass' and receivertype='flying';
update TYPEEFFECT set multfactor=50 where attackertype='grass' and receivertype='poison';
update TYPEEFFECT set multfactor=50 where attackertype='grass' and receivertype='bug';
update TYPEEFFECT set multfactor=50 where attackertype='grass' and receivertype='steel';
update TYPEEFFECT set multfactor=50 where attackertype='grass' and receivertype='fire';
update TYPEEFFECT set multfactor=50 where attackertype='grass' and receivertype='grass';
update TYPEEFFECT set multfactor=50 where attackertype='grass' and receivertype='dragon';
update TYPEEFFECT set multfactor=200 where attackertype='grass' and receivertype='ground';
update TYPEEFFECT set multfactor=200 where attackertype='grass' and receivertype='rock';
update TYPEEFFECT set multfactor=200 where attackertype='grass' and receivertype='water';
update TYPEEFFECT set multfactor=0 where attackertype='electric' and receivertype='ground';
update TYPEEFFECT set multfactor=50 where attackertype='electric' and receivertype='grass';
update TYPEEFFECT set multfactor=50 where attackertype='electric' and receivertype='electric';
update TYPEEFFECT set multfactor=50 where attackertype='electric' and receivertype='dragon';
update TYPEEFFECT set multfactor=200 where attackertype='electric' and receivertype='flying';
update TYPEEFFECT set multfactor=200 where attackertype='electric' and receivertype='water';
update TYPEEFFECT set multfactor=0 where attackertype='psychic' and receivertype='dark';
update TYPEEFFECT set multfactor=50 where attackertype='psychic' and receivertype='steel';
update TYPEEFFECT set multfactor=50 where attackertype='psychic' and receivertype='psychic';
update TYPEEFFECT set multfactor=200 where attackertype='psychic' and receivertype='fighting';
update TYPEEFFECT set multfactor=200 where attackertype='psychic' and receivertype='poison';
update TYPEEFFECT set multfactor=50 where attackertype='ice' and receivertype='steel';
update TYPEEFFECT set multfactor=50 where attackertype='ice' and receivertype='fire';
update TYPEEFFECT set multfactor=50 where attackertype='ice' and receivertype='water';
update TYPEEFFECT set multfactor=50 where attackertype='ice' and receivertype='ice';
update TYPEEFFECT set multfactor=200 where attackertype='ice' and receivertype='flying';
update TYPEEFFECT set multfactor=200 where attackertype='ice' and receivertype='ground';
update TYPEEFFECT set multfactor=200 where attackertype='ice' and receivertype='grass';
update TYPEEFFECT set multfactor=200 where attackertype='ice' and receivertype='dragon';
update TYPEEFFECT set multfactor=0 where attackertype='dragon' and receivertype='fairy';
update TYPEEFFECT set multfactor=50 where attackertype='dragon' and receivertype='steel';
update TYPEEFFECT set multfactor=200 where attackertype='dragon' and receivertype='dragon';
update TYPEEFFECT set multfactor=50 where attackertype='dark' and receivertype='fighting';
update TYPEEFFECT set multfactor=50 where attackertype='dark' and receivertype='dark';
update TYPEEFFECT set multfactor=50 where attackertype='dark' and receivertype='fairy';
update TYPEEFFECT set multfactor=200 where attackertype='dark' and receivertype='ghost';
update TYPEEFFECT set multfactor=200 where attackertype='dark' and receivertype='psychic';
update TYPEEFFECT set multfactor=50 where attackertype='fairy' and receivertype='poison';
update TYPEEFFECT set multfactor=50 where attackertype='fairy' and receivertype='steel';
update TYPEEFFECT set multfactor=50 where attackertype='fairy' and receivertype='fire';
update TYPEEFFECT set multfactor=200 where attackertype='fairy' and receivertype='fighting';
update TYPEEFFECT set multfactor=200 where attackertype='fairy' and receivertype='dragon';
update TYPEEFFECT set multfactor=200 where attackertype='fairy' and receivertype='dark';
