INSERT INTO TypeEffect VALUES ('normal','normal',100);
INSERT INTO TypeEffect VALUES ('normal','fighting',100);
INSERT INTO TypeEffect VALUES ('normal','flying',100);
INSERT INTO TypeEffect VALUES ('normal','poison',100);
INSERT INTO TypeEffect VALUES ('normal','ground',100);
INSERT INTO TypeEffect VALUES ('normal','rock',100);
INSERT INTO TypeEffect VALUES ('normal','bug',100);
INSERT INTO TypeEffect VALUES ('normal','ghost',100);
INSERT INTO TypeEffect VALUES ('normal','steel',100);
INSERT INTO TypeEffect VALUES ('normal','fire',100);
INSERT INTO TypeEffect VALUES ('normal','water',100);
INSERT INTO TypeEffect VALUES ('normal','grass',100);
INSERT INTO TypeEffect VALUES ('normal','electric',100);
INSERT INTO TypeEffect VALUES ('normal','psychic',100);
INSERT INTO TypeEffect VALUES ('normal','ice',100);
INSERT INTO TypeEffect VALUES ('normal','dragon',100);
INSERT INTO TypeEffect VALUES ('normal','dark',100);
INSERT INTO TypeEffect VALUES ('normal','fairy',100);
INSERT INTO TypeEffect VALUES ('fighting','normal',100);
INSERT INTO TypeEffect VALUES ('fighting','fighting',100);
INSERT INTO TypeEffect VALUES ('fighting','flying',100);
INSERT INTO TypeEffect VALUES ('fighting','poison',100);
INSERT INTO TypeEffect VALUES ('fighting','ground',100);
INSERT INTO TypeEffect VALUES ('fighting','rock',100);
INSERT INTO TypeEffect VALUES ('fighting','bug',100);
INSERT INTO TypeEffect VALUES ('fighting','ghost',100);
INSERT INTO TypeEffect VALUES ('fighting','steel',100);
INSERT INTO TypeEffect VALUES ('fighting','fire',100);
INSERT INTO TypeEffect VALUES ('fighting','water',100);
INSERT INTO TypeEffect VALUES ('fighting','grass',100);
INSERT INTO TypeEffect VALUES ('fighting','electric',100);
INSERT INTO TypeEffect VALUES ('fighting','psychic',100);
INSERT INTO TypeEffect VALUES ('fighting','ice',100);
INSERT INTO TypeEffect VALUES ('fighting','dragon',100);
INSERT INTO TypeEffect VALUES ('fighting','dark',100);
INSERT INTO TypeEffect VALUES ('fighting','fairy',100);
INSERT INTO TypeEffect VALUES ('flying','normal',100);
INSERT INTO TypeEffect VALUES ('flying','fighting',100);
INSERT INTO TypeEffect VALUES ('flying','flying',100);
INSERT INTO TypeEffect VALUES ('flying','poison',100);
INSERT INTO TypeEffect VALUES ('flying','ground',100);
INSERT INTO TypeEffect VALUES ('flying','rock',100);
INSERT INTO TypeEffect VALUES ('flying','bug',100);
INSERT INTO TypeEffect VALUES ('flying','ghost',100);
INSERT INTO TypeEffect VALUES ('flying','steel',100);
INSERT INTO TypeEffect VALUES ('flying','fire',100);
INSERT INTO TypeEffect VALUES ('flying','water',100);
INSERT INTO TypeEffect VALUES ('flying','grass',100);
INSERT INTO TypeEffect VALUES ('flying','electric',100);
INSERT INTO TypeEffect VALUES ('flying','psychic',100);
INSERT INTO TypeEffect VALUES ('flying','ice',100);
INSERT INTO TypeEffect VALUES ('flying','dragon',100);
INSERT INTO TypeEffect VALUES ('flying','dark',100);
INSERT INTO TypeEffect VALUES ('flying','fairy',100);
INSERT INTO TypeEffect VALUES ('poison','normal',100);
INSERT INTO TypeEffect VALUES ('poison','fighting',100);
INSERT INTO TypeEffect VALUES ('poison','flying',100);
INSERT INTO TypeEffect VALUES ('poison','poison',100);
INSERT INTO TypeEffect VALUES ('poison','ground',100);
INSERT INTO TypeEffect VALUES ('poison','rock',100);
INSERT INTO TypeEffect VALUES ('poison','bug',100);
INSERT INTO TypeEffect VALUES ('poison','ghost',100);
INSERT INTO TypeEffect VALUES ('poison','steel',100);
INSERT INTO TypeEffect VALUES ('poison','fire',100);
INSERT INTO TypeEffect VALUES ('poison','water',100);
INSERT INTO TypeEffect VALUES ('poison','grass',100);
INSERT INTO TypeEffect VALUES ('poison','electric',100);
INSERT INTO TypeEffect VALUES ('poison','psychic',100);
INSERT INTO TypeEffect VALUES ('poison','ice',100);
INSERT INTO TypeEffect VALUES ('poison','dragon',100);
INSERT INTO TypeEffect VALUES ('poison','dark',100);
INSERT INTO TypeEffect VALUES ('poison','fairy',100);
INSERT INTO TypeEffect VALUES ('ground','normal',100);
INSERT INTO TypeEffect VALUES ('ground','fighting',100);
INSERT INTO TypeEffect VALUES ('ground','flying',100);
INSERT INTO TypeEffect VALUES ('ground','poison',100);
INSERT INTO TypeEffect VALUES ('ground','ground',100);
INSERT INTO TypeEffect VALUES ('ground','rock',100);
INSERT INTO TypeEffect VALUES ('ground','bug',100);
INSERT INTO TypeEffect VALUES ('ground','ghost',100);
INSERT INTO TypeEffect VALUES ('ground','steel',100);
INSERT INTO TypeEffect VALUES ('ground','fire',100);
INSERT INTO TypeEffect VALUES ('ground','water',100);
INSERT INTO TypeEffect VALUES ('ground','grass',100);
INSERT INTO TypeEffect VALUES ('ground','electric',100);
INSERT INTO TypeEffect VALUES ('ground','psychic',100);
INSERT INTO TypeEffect VALUES ('ground','ice',100);
INSERT INTO TypeEffect VALUES ('ground','dragon',100);
INSERT INTO TypeEffect VALUES ('ground','dark',100);
INSERT INTO TypeEffect VALUES ('ground','fairy',100);
INSERT INTO TypeEffect VALUES ('rock','normal',100);
INSERT INTO TypeEffect VALUES ('rock','fighting',100);
INSERT INTO TypeEffect VALUES ('rock','flying',100);
INSERT INTO TypeEffect VALUES ('rock','poison',100);
INSERT INTO TypeEffect VALUES ('rock','ground',100);
INSERT INTO TypeEffect VALUES ('rock','rock',100);
INSERT INTO TypeEffect VALUES ('rock','bug',100);
INSERT INTO TypeEffect VALUES ('rock','ghost',100);
INSERT INTO TypeEffect VALUES ('rock','steel',100);
INSERT INTO TypeEffect VALUES ('rock','fire',100);
INSERT INTO TypeEffect VALUES ('rock','water',100);
INSERT INTO TypeEffect VALUES ('rock','grass',100);
INSERT INTO TypeEffect VALUES ('rock','electric',100);
INSERT INTO TypeEffect VALUES ('rock','psychic',100);
INSERT INTO TypeEffect VALUES ('rock','ice',100);
INSERT INTO TypeEffect VALUES ('rock','dragon',100);
INSERT INTO TypeEffect VALUES ('rock','dark',100);
INSERT INTO TypeEffect VALUES ('rock','fairy',100);
INSERT INTO TypeEffect VALUES ('bug','normal',100);
INSERT INTO TypeEffect VALUES ('bug','fighting',100);
INSERT INTO TypeEffect VALUES ('bug','flying',100);
INSERT INTO TypeEffect VALUES ('bug','poison',100);
INSERT INTO TypeEffect VALUES ('bug','ground',100);
INSERT INTO TypeEffect VALUES ('bug','rock',100);
INSERT INTO TypeEffect VALUES ('bug','bug',100);
INSERT INTO TypeEffect VALUES ('bug','ghost',100);
INSERT INTO TypeEffect VALUES ('bug','steel',100);
INSERT INTO TypeEffect VALUES ('bug','fire',100);
INSERT INTO TypeEffect VALUES ('bug','water',100);
INSERT INTO TypeEffect VALUES ('bug','grass',100);
INSERT INTO TypeEffect VALUES ('bug','electric',100);
INSERT INTO TypeEffect VALUES ('bug','psychic',100);
INSERT INTO TypeEffect VALUES ('bug','ice',100);
INSERT INTO TypeEffect VALUES ('bug','dragon',100);
INSERT INTO TypeEffect VALUES ('bug','dark',100);
INSERT INTO TypeEffect VALUES ('bug','fairy',100);
INSERT INTO TypeEffect VALUES ('ghost','normal',100);
INSERT INTO TypeEffect VALUES ('ghost','fighting',100);
INSERT INTO TypeEffect VALUES ('ghost','flying',100);
INSERT INTO TypeEffect VALUES ('ghost','poison',100);
INSERT INTO TypeEffect VALUES ('ghost','ground',100);
INSERT INTO TypeEffect VALUES ('ghost','rock',100);
INSERT INTO TypeEffect VALUES ('ghost','bug',100);
INSERT INTO TypeEffect VALUES ('ghost','ghost',100);
INSERT INTO TypeEffect VALUES ('ghost','steel',100);
INSERT INTO TypeEffect VALUES ('ghost','fire',100);
INSERT INTO TypeEffect VALUES ('ghost','water',100);
INSERT INTO TypeEffect VALUES ('ghost','grass',100);
INSERT INTO TypeEffect VALUES ('ghost','electric',100);
INSERT INTO TypeEffect VALUES ('ghost','psychic',100);
INSERT INTO TypeEffect VALUES ('ghost','ice',100);
INSERT INTO TypeEffect VALUES ('ghost','dragon',100);
INSERT INTO TypeEffect VALUES ('ghost','dark',100);
INSERT INTO TypeEffect VALUES ('ghost','fairy',100);
INSERT INTO TypeEffect VALUES ('steel','normal',100);
INSERT INTO TypeEffect VALUES ('steel','fighting',100);
INSERT INTO TypeEffect VALUES ('steel','flying',100);
INSERT INTO TypeEffect VALUES ('steel','poison',100);
INSERT INTO TypeEffect VALUES ('steel','ground',100);
INSERT INTO TypeEffect VALUES ('steel','rock',100);
INSERT INTO TypeEffect VALUES ('steel','bug',100);
INSERT INTO TypeEffect VALUES ('steel','ghost',100);
INSERT INTO TypeEffect VALUES ('steel','steel',100);
INSERT INTO TypeEffect VALUES ('steel','fire',100);
INSERT INTO TypeEffect VALUES ('steel','water',100);
INSERT INTO TypeEffect VALUES ('steel','grass',100);
INSERT INTO TypeEffect VALUES ('steel','electric',100);
INSERT INTO TypeEffect VALUES ('steel','psychic',100);
INSERT INTO TypeEffect VALUES ('steel','ice',100);
INSERT INTO TypeEffect VALUES ('steel','dragon',100);
INSERT INTO TypeEffect VALUES ('steel','dark',100);
INSERT INTO TypeEffect VALUES ('steel','fairy',100);
INSERT INTO TypeEffect VALUES ('fire','normal',100);
INSERT INTO TypeEffect VALUES ('fire','fighting',100);
INSERT INTO TypeEffect VALUES ('fire','flying',100);
INSERT INTO TypeEffect VALUES ('fire','poison',100);
INSERT INTO TypeEffect VALUES ('fire','ground',100);
INSERT INTO TypeEffect VALUES ('fire','rock',100);
INSERT INTO TypeEffect VALUES ('fire','bug',100);
INSERT INTO TypeEffect VALUES ('fire','ghost',100);
INSERT INTO TypeEffect VALUES ('fire','steel',100);
INSERT INTO TypeEffect VALUES ('fire','fire',100);
INSERT INTO TypeEffect VALUES ('fire','water',100);
INSERT INTO TypeEffect VALUES ('fire','grass',100);
INSERT INTO TypeEffect VALUES ('fire','electric',100);
INSERT INTO TypeEffect VALUES ('fire','psychic',100);
INSERT INTO TypeEffect VALUES ('fire','ice',100);
INSERT INTO TypeEffect VALUES ('fire','dragon',100);
INSERT INTO TypeEffect VALUES ('fire','dark',100);
INSERT INTO TypeEffect VALUES ('fire','fairy',100);
INSERT INTO TypeEffect VALUES ('water','normal',100);
INSERT INTO TypeEffect VALUES ('water','fighting',100);
INSERT INTO TypeEffect VALUES ('water','flying',100);
INSERT INTO TypeEffect VALUES ('water','poison',100);
INSERT INTO TypeEffect VALUES ('water','ground',100);
INSERT INTO TypeEffect VALUES ('water','rock',100);
INSERT INTO TypeEffect VALUES ('water','bug',100);
INSERT INTO TypeEffect VALUES ('water','ghost',100);
INSERT INTO TypeEffect VALUES ('water','steel',100);
INSERT INTO TypeEffect VALUES ('water','fire',100);
INSERT INTO TypeEffect VALUES ('water','water',100);
INSERT INTO TypeEffect VALUES ('water','grass',100);
INSERT INTO TypeEffect VALUES ('water','electric',100);
INSERT INTO TypeEffect VALUES ('water','psychic',100);
INSERT INTO TypeEffect VALUES ('water','ice',100);
INSERT INTO TypeEffect VALUES ('water','dragon',100);
INSERT INTO TypeEffect VALUES ('water','dark',100);
INSERT INTO TypeEffect VALUES ('water','fairy',100);
INSERT INTO TypeEffect VALUES ('grass','normal',100);
INSERT INTO TypeEffect VALUES ('grass','fighting',100);
INSERT INTO TypeEffect VALUES ('grass','flying',100);
INSERT INTO TypeEffect VALUES ('grass','poison',100);
INSERT INTO TypeEffect VALUES ('grass','ground',100);
INSERT INTO TypeEffect VALUES ('grass','rock',100);
INSERT INTO TypeEffect VALUES ('grass','bug',100);
INSERT INTO TypeEffect VALUES ('grass','ghost',100);
INSERT INTO TypeEffect VALUES ('grass','steel',100);
INSERT INTO TypeEffect VALUES ('grass','fire',100);
INSERT INTO TypeEffect VALUES ('grass','water',100);
INSERT INTO TypeEffect VALUES ('grass','grass',100);
INSERT INTO TypeEffect VALUES ('grass','electric',100);
INSERT INTO TypeEffect VALUES ('grass','psychic',100);
INSERT INTO TypeEffect VALUES ('grass','ice',100);
INSERT INTO TypeEffect VALUES ('grass','dragon',100);
INSERT INTO TypeEffect VALUES ('grass','dark',100);
INSERT INTO TypeEffect VALUES ('grass','fairy',100);
INSERT INTO TypeEffect VALUES ('electric','normal',100);
INSERT INTO TypeEffect VALUES ('electric','fighting',100);
INSERT INTO TypeEffect VALUES ('electric','flying',100);
INSERT INTO TypeEffect VALUES ('electric','poison',100);
INSERT INTO TypeEffect VALUES ('electric','ground',100);
INSERT INTO TypeEffect VALUES ('electric','rock',100);
INSERT INTO TypeEffect VALUES ('electric','bug',100);
INSERT INTO TypeEffect VALUES ('electric','ghost',100);
INSERT INTO TypeEffect VALUES ('electric','steel',100);
INSERT INTO TypeEffect VALUES ('electric','fire',100);
INSERT INTO TypeEffect VALUES ('electric','water',100);
INSERT INTO TypeEffect VALUES ('electric','grass',100);
INSERT INTO TypeEffect VALUES ('electric','electric',100);
INSERT INTO TypeEffect VALUES ('electric','psychic',100);
INSERT INTO TypeEffect VALUES ('electric','ice',100);
INSERT INTO TypeEffect VALUES ('electric','dragon',100);
INSERT INTO TypeEffect VALUES ('electric','dark',100);
INSERT INTO TypeEffect VALUES ('electric','fairy',100);
INSERT INTO TypeEffect VALUES ('psychic','normal',100);
INSERT INTO TypeEffect VALUES ('psychic','fighting',100);
INSERT INTO TypeEffect VALUES ('psychic','flying',100);
INSERT INTO TypeEffect VALUES ('psychic','poison',100);
INSERT INTO TypeEffect VALUES ('psychic','ground',100);
INSERT INTO TypeEffect VALUES ('psychic','rock',100);
INSERT INTO TypeEffect VALUES ('psychic','bug',100);
INSERT INTO TypeEffect VALUES ('psychic','ghost',100);
INSERT INTO TypeEffect VALUES ('psychic','steel',100);
INSERT INTO TypeEffect VALUES ('psychic','fire',100);
INSERT INTO TypeEffect VALUES ('psychic','water',100);
INSERT INTO TypeEffect VALUES ('psychic','grass',100);
INSERT INTO TypeEffect VALUES ('psychic','electric',100);
INSERT INTO TypeEffect VALUES ('psychic','psychic',100);
INSERT INTO TypeEffect VALUES ('psychic','ice',100);
INSERT INTO TypeEffect VALUES ('psychic','dragon',100);
INSERT INTO TypeEffect VALUES ('psychic','dark',100);
INSERT INTO TypeEffect VALUES ('psychic','fairy',100);
INSERT INTO TypeEffect VALUES ('ice','normal',100);
INSERT INTO TypeEffect VALUES ('ice','fighting',100);
INSERT INTO TypeEffect VALUES ('ice','flying',100);
INSERT INTO TypeEffect VALUES ('ice','poison',100);
INSERT INTO TypeEffect VALUES ('ice','ground',100);
INSERT INTO TypeEffect VALUES ('ice','rock',100);
INSERT INTO TypeEffect VALUES ('ice','bug',100);
INSERT INTO TypeEffect VALUES ('ice','ghost',100);
INSERT INTO TypeEffect VALUES ('ice','steel',100);
INSERT INTO TypeEffect VALUES ('ice','fire',100);
INSERT INTO TypeEffect VALUES ('ice','water',100);
INSERT INTO TypeEffect VALUES ('ice','grass',100);
INSERT INTO TypeEffect VALUES ('ice','electric',100);
INSERT INTO TypeEffect VALUES ('ice','psychic',100);
INSERT INTO TypeEffect VALUES ('ice','ice',100);
INSERT INTO TypeEffect VALUES ('ice','dragon',100);
INSERT INTO TypeEffect VALUES ('ice','dark',100);
INSERT INTO TypeEffect VALUES ('ice','fairy',100);
INSERT INTO TypeEffect VALUES ('dragon','normal',100);
INSERT INTO TypeEffect VALUES ('dragon','fighting',100);
INSERT INTO TypeEffect VALUES ('dragon','flying',100);
INSERT INTO TypeEffect VALUES ('dragon','poison',100);
INSERT INTO TypeEffect VALUES ('dragon','ground',100);
INSERT INTO TypeEffect VALUES ('dragon','rock',100);
INSERT INTO TypeEffect VALUES ('dragon','bug',100);
INSERT INTO TypeEffect VALUES ('dragon','ghost',100);
INSERT INTO TypeEffect VALUES ('dragon','steel',100);
INSERT INTO TypeEffect VALUES ('dragon','fire',100);
INSERT INTO TypeEffect VALUES ('dragon','water',100);
INSERT INTO TypeEffect VALUES ('dragon','grass',100);
INSERT INTO TypeEffect VALUES ('dragon','electric',100);
INSERT INTO TypeEffect VALUES ('dragon','psychic',100);
INSERT INTO TypeEffect VALUES ('dragon','ice',100);
INSERT INTO TypeEffect VALUES ('dragon','dragon',100);
INSERT INTO TypeEffect VALUES ('dragon','dark',100);
INSERT INTO TypeEffect VALUES ('dragon','fairy',100);
INSERT INTO TypeEffect VALUES ('dark','normal',100);
INSERT INTO TypeEffect VALUES ('dark','fighting',100);
INSERT INTO TypeEffect VALUES ('dark','flying',100);
INSERT INTO TypeEffect VALUES ('dark','poison',100);
INSERT INTO TypeEffect VALUES ('dark','ground',100);
INSERT INTO TypeEffect VALUES ('dark','rock',100);
INSERT INTO TypeEffect VALUES ('dark','bug',100);
INSERT INTO TypeEffect VALUES ('dark','ghost',100);
INSERT INTO TypeEffect VALUES ('dark','steel',100);
INSERT INTO TypeEffect VALUES ('dark','fire',100);
INSERT INTO TypeEffect VALUES ('dark','water',100);
INSERT INTO TypeEffect VALUES ('dark','grass',100);
INSERT INTO TypeEffect VALUES ('dark','electric',100);
INSERT INTO TypeEffect VALUES ('dark','psychic',100);
INSERT INTO TypeEffect VALUES ('dark','ice',100);
INSERT INTO TypeEffect VALUES ('dark','dragon',100);
INSERT INTO TypeEffect VALUES ('dark','dark',100);
INSERT INTO TypeEffect VALUES ('dark','fairy',100);
INSERT INTO TypeEffect VALUES ('fairy','normal',100);
INSERT INTO TypeEffect VALUES ('fairy','fighting',100);
INSERT INTO TypeEffect VALUES ('fairy','flying',100);
INSERT INTO TypeEffect VALUES ('fairy','poison',100);
INSERT INTO TypeEffect VALUES ('fairy','ground',100);
INSERT INTO TypeEffect VALUES ('fairy','rock',100);
INSERT INTO TypeEffect VALUES ('fairy','bug',100);
INSERT INTO TypeEffect VALUES ('fairy','ghost',100);
INSERT INTO TypeEffect VALUES ('fairy','steel',100);
INSERT INTO TypeEffect VALUES ('fairy','fire',100);
INSERT INTO TypeEffect VALUES ('fairy','water',100);
INSERT INTO TypeEffect VALUES ('fairy','grass',100);
INSERT INTO TypeEffect VALUES ('fairy','electric',100);
INSERT INTO TypeEffect VALUES ('fairy','psychic',100);
INSERT INTO TypeEffect VALUES ('fairy','ice',100);
INSERT INTO TypeEffect VALUES ('fairy','dragon',100);
INSERT INTO TypeEffect VALUES ('fairy','dark',100);
INSERT INTO TypeEffect VALUES ('fairy','fairy',100);
update TypeEffect set multfactor=0 where attackertype='normal' and receivertype='ghost';
update TypeEffect set multfactor=50 where attackertype='normal' and receivertype='rock';
update TypeEffect set multfactor=50 where attackertype='normal' and receivertype='steel';
update TypeEffect set multfactor=0 where attackertype='fighting' and receivertype='ghost';
update TypeEffect set multfactor=50 where attackertype='fighting' and receivertype='flying';
update TypeEffect set multfactor=50 where attackertype='fighting' and receivertype='poison';
update TypeEffect set multfactor=50 where attackertype='fighting' and receivertype='bug';
update TypeEffect set multfactor=50 where attackertype='fighting' and receivertype='psychic';
update TypeEffect set multfactor=50 where attackertype='fighting' and receivertype='fairy';
update TypeEffect set multfactor=200 where attackertype='fighting' and receivertype='normal';
update TypeEffect set multfactor=200 where attackertype='fighting' and receivertype='rock';
update TypeEffect set multfactor=200 where attackertype='fighting' and receivertype='steel';
update TypeEffect set multfactor=200 where attackertype='fighting' and receivertype='ice';
update TypeEffect set multfactor=200 where attackertype='fighting' and receivertype='dark';
update TypeEffect set multfactor=50 where attackertype='flying' and receivertype='rock';
update TypeEffect set multfactor=50 where attackertype='flying' and receivertype='steel';
update TypeEffect set multfactor=50 where attackertype='flying' and receivertype='electric';
update TypeEffect set multfactor=200 where attackertype='flying' and receivertype='fighting';
update TypeEffect set multfactor=200 where attackertype='flying' and receivertype='bug';
update TypeEffect set multfactor=200 where attackertype='flying' and receivertype='grass';
update TypeEffect set multfactor=0 where attackertype='poison' and receivertype='steel';
update TypeEffect set multfactor=50 where attackertype='poison' and receivertype='poison';
update TypeEffect set multfactor=50 where attackertype='poison' and receivertype='ground';
update TypeEffect set multfactor=50 where attackertype='poison' and receivertype='rock';
update TypeEffect set multfactor=50 where attackertype='poison' and receivertype='ghost';
update TypeEffect set multfactor=200 where attackertype='poison' and receivertype='grass';
update TypeEffect set multfactor=200 where attackertype='poison' and receivertype='fairy';
update TypeEffect set multfactor=0 where attackertype='ground' and receivertype='flying';
update TypeEffect set multfactor=50 where attackertype='ground' and receivertype='bug';
update TypeEffect set multfactor=50 where attackertype='ground' and receivertype='grass';
update TypeEffect set multfactor=200 where attackertype='ground' and receivertype='poison';
update TypeEffect set multfactor=200 where attackertype='ground' and receivertype='rock';
update TypeEffect set multfactor=200 where attackertype='ground' and receivertype='steel';
update TypeEffect set multfactor=200 where attackertype='ground' and receivertype='fire';
update TypeEffect set multfactor=200 where attackertype='ground' and receivertype='electric';
update TypeEffect set multfactor=50 where attackertype='rock' and receivertype='fighting';
update TypeEffect set multfactor=50 where attackertype='rock' and receivertype='ground';
update TypeEffect set multfactor=50 where attackertype='rock' and receivertype='steel';
update TypeEffect set multfactor=200 where attackertype='rock' and receivertype='flying';
update TypeEffect set multfactor=200 where attackertype='rock' and receivertype='bug';
update TypeEffect set multfactor=200 where attackertype='rock' and receivertype='fire';
update TypeEffect set multfactor=200 where attackertype='rock' and receivertype='ice';
update TypeEffect set multfactor=50 where attackertype='bug' and receivertype='fighting';
update TypeEffect set multfactor=50 where attackertype='bug' and receivertype='flying';
update TypeEffect set multfactor=50 where attackertype='bug' and receivertype='poison';
update TypeEffect set multfactor=50 where attackertype='bug' and receivertype='ghost';
update TypeEffect set multfactor=50 where attackertype='bug' and receivertype='steel';
update TypeEffect set multfactor=50 where attackertype='bug' and receivertype='fire';
update TypeEffect set multfactor=50 where attackertype='bug' and receivertype='fairy';
update TypeEffect set multfactor=200 where attackertype='bug' and receivertype='grass';
update TypeEffect set multfactor=200 where attackertype='bug' and receivertype='psychic';
update TypeEffect set multfactor=200 where attackertype='bug' and receivertype='dark';
update TypeEffect set multfactor=0 where attackertype='ghost' and receivertype='normal';
update TypeEffect set multfactor=50 where attackertype='ghost' and receivertype='dark';
update TypeEffect set multfactor=200 where attackertype='ghost' and receivertype='ghost';
update TypeEffect set multfactor=200 where attackertype='ghost' and receivertype='psychic';
update TypeEffect set multfactor=50 where attackertype='steel' and receivertype='steel';
update TypeEffect set multfactor=50 where attackertype='steel' and receivertype='fire';
update TypeEffect set multfactor=50 where attackertype='steel' and receivertype='water';
update TypeEffect set multfactor=50 where attackertype='steel' and receivertype='electric';
update TypeEffect set multfactor=200 where attackertype='steel' and receivertype='rock';
update TypeEffect set multfactor=200 where attackertype='steel' and receivertype='ice';
update TypeEffect set multfactor=200 where attackertype='steel' and receivertype='fairy';
update TypeEffect set multfactor=50 where attackertype='fire' and receivertype='rock';
update TypeEffect set multfactor=50 where attackertype='fire' and receivertype='fire';
update TypeEffect set multfactor=50 where attackertype='fire' and receivertype='water';
update TypeEffect set multfactor=50 where attackertype='fire' and receivertype='dragon';
update TypeEffect set multfactor=200 where attackertype='fire' and receivertype='bug';
update TypeEffect set multfactor=200 where attackertype='fire' and receivertype='steel';
update TypeEffect set multfactor=200 where attackertype='fire' and receivertype='grass';
update TypeEffect set multfactor=200 where attackertype='fire' and receivertype='ice';
update TypeEffect set multfactor=50 where attackertype='water' and receivertype='water';
update TypeEffect set multfactor=50 where attackertype='water' and receivertype='grass';
update TypeEffect set multfactor=50 where attackertype='water' and receivertype='dragon';
update TypeEffect set multfactor=200 where attackertype='water' and receivertype='ground';
update TypeEffect set multfactor=200 where attackertype='water' and receivertype='rock';
update TypeEffect set multfactor=200 where attackertype='water' and receivertype='fire';
update TypeEffect set multfactor=50 where attackertype='grass' and receivertype='flying';
update TypeEffect set multfactor=50 where attackertype='grass' and receivertype='poison';
update TypeEffect set multfactor=50 where attackertype='grass' and receivertype='bug';
update TypeEffect set multfactor=50 where attackertype='grass' and receivertype='steel';
update TypeEffect set multfactor=50 where attackertype='grass' and receivertype='fire';
update TypeEffect set multfactor=50 where attackertype='grass' and receivertype='grass';
update TypeEffect set multfactor=50 where attackertype='grass' and receivertype='dragon';
update TypeEffect set multfactor=200 where attackertype='grass' and receivertype='ground';
update TypeEffect set multfactor=200 where attackertype='grass' and receivertype='rock';
update TypeEffect set multfactor=200 where attackertype='grass' and receivertype='water';
update TypeEffect set multfactor=0 where attackertype='electric' and receivertype='ground';
update TypeEffect set multfactor=50 where attackertype='electric' and receivertype='grass';
update TypeEffect set multfactor=50 where attackertype='electric' and receivertype='electric';
update TypeEffect set multfactor=50 where attackertype='electric' and receivertype='dragon';
update TypeEffect set multfactor=200 where attackertype='electric' and receivertype='flying';
update TypeEffect set multfactor=200 where attackertype='electric' and receivertype='water';
update TypeEffect set multfactor=0 where attackertype='psychic' and receivertype='dark';
update TypeEffect set multfactor=50 where attackertype='psychic' and receivertype='steel';
update TypeEffect set multfactor=50 where attackertype='psychic' and receivertype='psychic';
update TypeEffect set multfactor=200 where attackertype='psychic' and receivertype='fighting';
update TypeEffect set multfactor=200 where attackertype='psychic' and receivertype='poison';
update TypeEffect set multfactor=50 where attackertype='ice' and receivertype='steel';
update TypeEffect set multfactor=50 where attackertype='ice' and receivertype='fire';
update TypeEffect set multfactor=50 where attackertype='ice' and receivertype='water';
update TypeEffect set multfactor=50 where attackertype='ice' and receivertype='ice';
update TypeEffect set multfactor=200 where attackertype='ice' and receivertype='flying';
update TypeEffect set multfactor=200 where attackertype='ice' and receivertype='ground';
update TypeEffect set multfactor=200 where attackertype='ice' and receivertype='grass';
update TypeEffect set multfactor=200 where attackertype='ice' and receivertype='dragon';
update TypeEffect set multfactor=0 where attackertype='dragon' and receivertype='fairy';
update TypeEffect set multfactor=50 where attackertype='dragon' and receivertype='steel';
update TypeEffect set multfactor=200 where attackertype='dragon' and receivertype='dragon';
update TypeEffect set multfactor=50 where attackertype='dark' and receivertype='fighting';
update TypeEffect set multfactor=50 where attackertype='dark' and receivertype='dark';
update TypeEffect set multfactor=50 where attackertype='dark' and receivertype='fairy';
update TypeEffect set multfactor=200 where attackertype='dark' and receivertype='ghost';
update TypeEffect set multfactor=200 where attackertype='dark' and receivertype='psychic';
update TypeEffect set multfactor=50 where attackertype='fairy' and receivertype='poison';
update TypeEffect set multfactor=50 where attackertype='fairy' and receivertype='steel';
update TypeEffect set multfactor=50 where attackertype='fairy' and receivertype='fire';
update TypeEffect set multfactor=200 where attackertype='fairy' and receivertype='fighting';
update TypeEffect set multfactor=200 where attackertype='fairy' and receivertype='dragon';
update TypeEffect set multfactor=200 where attackertype='fairy' and receivertype='dark';
